---
# Source: opa-operator/templates/configmap.yaml
apiVersion: v1
data:
  properties.yaml: |-
    version: 0.1.0
    spec:
      units:
        - unit: &unitUrl
            name: "url"
            regex: "^((https?|ftp|file)://)?[-a-zA-Z0-9+&@#}/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]"
            examples:
              - "https://www.stackable.de/blog/"
  
    properties:
      - property: &opaRegoRuleReference
          propertyNames:
            - name: "regoRuleReference"
              kind:
                type: "file"
                file: "config.yaml"
          datatype:
            type: "string"
            unit: *unitUrl
          defaultValues:
            - fromVersion: "0.0.0"
              value: "http://regorule-operator:3030/opa/v1"
          roles:
            - name: "server"
              required: true
          asOfVersion: "0.0.0"
          description: "The url of the RegoRule server"
kind: ConfigMap
metadata:
  name: opa-operator-configmap
  labels:
    helm.sh/chart: opa-operator-0.8.0-nightly
    app.kubernetes.io/name: opa-operator
    app.kubernetes.io/instance: opa-operator
    app.kubernetes.io/version: "0.8.0-nightly"
    app.kubernetes.io/managed-by: Helm
