---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opa-operator-clusterrole
rules:
  # For OPA dependents. Note that OPA it's self is listed here because it's own resource name
  # doesn't follow the *clusters convention
  - apiGroups:
      - opa.stackable.tech
    resources:
      - openpolicyagents
      - openpolicyagents/status
      - regorules
    verbs:
      - create
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - endpoints
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebinding
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - create
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - command.opa.stackable.tech
    resources:
      - inits
      - restarts
      - starts
      - stops
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - command.opa.stackable.tech
    resources:
      - inits/status
    verbs:
      - patch
  - apiGroups:
      - opa.stackable.tech
    resources:
      - opaclusters
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - opa.stackable.tech
    resources:
      - opaclusters/status
    verbs:
      - patch
