apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-opa-bundle-builder-clusterrole
# This role is used for the OPA bundle builder.
# It needs to read ConfigMaps and watch ConfigMaps for changes,
# because the Rego rules that are used to build the bundles are
# stored in the ConfigMaps.
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
{{ if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - opa-scc
    verbs:
      - use
{{ end }}
