= First steps
:description: Set up the OPA with Stackable operator, deploy your first policy rule, and query it from the command line in Kubernetes.
:docs-policy-language: https://www.openpolicyagent.org/docs/latest/policy-language/

After you went through the xref:getting_started/installation.adoc[], on this page you deploy OPA, deploy your first rule and query it from the command line.

== Deploy OPA

To deploy OPA, you create an OpaCluster resource in Kubernetes and the operator creates the OPA Stacklet.
Create a file called `opa.yaml` with the following contents:

[source,yaml]
include::example$getting_started/opa.yaml[]

and apply it:

[source,bash]
include::example$getting_started/getting_started.sh[tag=apply-opa-cluster]

This creates an OPA cluster.
The operator deploys a DaemonSet, which means that an OPA Pod is deployed on every Node of the cluster.
This reduces network traffic and improves latency for decision requests, since every other Pod making decision requests only has to make its request to another port on the same Node.

== Deploy a policy rule

Now deploy the first {docs-policy-language}[policy rule] to OPA.
Rules are deployed in ConfigMaps.
Create a file `simple-rule.yaml` with the following contents:

[source,yaml]
----
include::example$getting_started/simple-rule.yaml[]
----

and apply it:

[source,bash]
include::example$getting_started/getting_started.sh[tag=apply-rule-file]

The operator reads the rule file, bundles it and publishes the bundle to all OPA Pods in the cluster.

== Make policy requests

Now that you have deployed the rule, you can query OPA for it.
First, port-forward the service so you can query it from outside the Kubernetes cluster:

[source,bash]
include::example$getting_started/getting_started.sh[tag=port-forwarding]

Then, request the `hello` rule:

[source,bash]
include::example$getting_started/getting_started.sh[tag=request-hello]

As it was defined in the rule file, the response should be `true`:

[source,json]
include::example$getting_started/expected_response_hello.json[]

You can also request the other rule, `world`:

[source,bash]
include::example$getting_started/getting_started.sh[tag=request-world]

And see a different response:

[source,json]
include::example$getting_started/expected_response_world.json[]

Great! You've set up OPA, deployed a rule and queried it!

== What's next

Have a look at the xref:usage-guide/index.adoc[] page for more configuration options of the operator.
