= Installation
:description: Install the Stackable OPA operator on Kubernetes using stackablectl or Helm. Deploy OPA, create policies, and query rules easily.

There are 2 ways to install Stackable operators on a Kubernetes cluster.

* Using xref:management:stackablectl:index.adoc[] (recommended)
* Using Helm

[tabs]
====
stackablectl::
+
--
`stackablectl` is the command line tool to interact with Stackable operators and the recommended way to install operators.
Follow the xref:management:stackablectl:installation.adoc[installation steps] for your platform.

After you have installed `stackablectl` run the following command to install the OPA operator:

[source,shell]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-operators]
----

The tool prints

[source]
include::example$getting_started/install_output.txt[]

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`.
For example, you can use the `--cluster kind` flag to create a Kubernetes cluster with link:https://kind.sigs.k8s.io/[kind].
--

Helm::
+
--
You can also use Helm to install the operator.
Add the Stackable Helm repository:

[source,shell]
----
include::example$getting_started/getting_started.sh[tag=helm-add-repo]
----

Then install the Stackable OPA operator:

[source,shell]
----
include::example$getting_started/getting_started.sh[tag=helm-install-operators]
----

Helm deploys the operator in a Kubernetes Deployment and apply the CRDs for the OPA service.
--
====

== What's next

xref:getting_started/first_steps.adoc[Deploy OPA, a policy rule and query it].
