[package]
name = "stackable-opa-user-info-fetcher"
version = "0.0.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.39.0" }
stackable-opa-crd = { path = "../crd" }

clap = "4.1"
futures = { version = "0.3", features = ["compat"] }
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
snafu = "0.7"
tokio = { version = "1.25", features = ["full"] }
tracing = "0.1"
pin-project = "1.0"
axum = "0.6.15"
reqwest = { version = "0.11.16", features = ["json"] }
