= Implementation Notes

These notes may be of use when trying to understand why things are implemented the way that they are,
but should not be required reading for regular use.

== OPA replica per Node

We run an OPA on each node, because we want to avoid requiring network round trips for services making
policy queries (which are often chained in serial, and block other tasks in the products).

We ensure local access via an https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/[`InternalTrafficPolicy`]. This means that https://kubernetes.io/docs/concepts/workloads/pods/[`Pods`] accessing OPA via the service discovery will be routed to the OPA `Pod` on the same https://kubernetes.io/docs/concepts/architecture/nodes/[`Node`] to reduce request latency and network traffic. This feature is only activated per default in Kubernetes versions https://github.com/kubernetes/kubernetes/pull/103462[`1.22`] or higher.

== OPA Bundle Builder

Users can manage the Rego-rules evaluated by an OPA cluster by creating, updating and deleting `ConfigMap` resources.

The role of the bundle builder is to convert these ressources to bundles (`tar.gz` files) that are loaded by OPA regularly.
The bundle builder runs in a side container of the OPA `Pod`s as a simple HTTP server that OPA uses for Rego-rule ingestion.

Users have to label `ConfigMap` ressources with `opa.stackable.tech/bundle` and provide a `name` property that is used as
file name to store the rules themselves in the bundle.

NOTE: Kubernetes limits the size of `ConfigMap`s to 1MB. Users have to take this limit into consideration when manging Rego-rules.
