= Implementation Notes

These notes may be of use when trying to understand why things are implemented the way that they are,
but should not be required reading for regular use.

== OPA replica per Node

We run an OPA on each node, because we want to avoid requiring network round trips for services making
policy queries (which are often chained in serial, and block other tasks in the products).

We ensure local access via an https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/[`InternalTrafficPolicy`]. This means that https://kubernetes.io/docs/concepts/workloads/pods/[`Pods`] accessing OPA via the service discovery will be routed to the OPA `Pod` on the same https://kubernetes.io/docs/concepts/architecture/nodes/[`Node`] to reduce request latency and network traffic. This feature is only activated per default in Kubernetes versions https://github.com/kubernetes/kubernetes/pull/103462[`1.22`] or higher.

== OPA Bundle Builder

Users can manage the Rego-rules evaluated by an OPA cluster by creating, updating and deleting `ConfigMap` resources.

The role of the bundle builder is to convert these ressources to bundles (`tar.gz` files) and make it available as a HTTP endpoint.
The bundle builder runs in a side container of the OPA `Pod` as a simple HTTP server that OPA querying regularly
(every 20 to 30 seconds) for updates.

NOTE: Kubernetes limits the size of `ConfigMap`s to 1MB. Users have to take this limit into consideration when manging Rego-rules.

Only `ConfigMap`s labeled with `opa.stackable.tech/bundle` are watched by the builder when updating bundles. The name of
the `data` entries in the `ConfigMap` are used as file names when storing the rules in the bundle.

NOTE: Currently it is the user's responsability to make sure these names do not collide.
