= Usage

After installation, the CRD for this operator must be created:

[source]
----
kubectl apply -f /etc/stackable/opa-operator/crd/openpolicyagent.crd.yaml
----

To create a single node OPA (v0.27.1) cluster with Prometheus metrics exposed on port 8081:

[source,yaml]
----
    apiVersion: opa.stackable.tech/v1alpha1
    kind: OpenPolicyAgent
    metadata:
      name: simple-opa
    spec:
      version: "0.27.1"
      servers:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/os: linux
            config:
              regoRuleReference: "http://regorule-operator:3030/opa/v1"
----

== Bundle sources

The OPA servers can load bundles from a remote server by specifying the `regoRuleReference` property as shown above.

Alternatively, bundles can be loaded from `ConfigMap` objects created in the same namespace as the OPA pod. These `ConfigMap`s
must be labeled with `opa.stackable.tech/bundle`.

== Monitoring

The managed OPA instances are automatically configured to export Prometheus metrics. See
xref:home::monitoring.adoc[] for more details.

== Configuration & Environment Overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Do not override port numbers. This will lead to faulty installations.

=== Configuration Properties

Currently, not supported for `config.yaml`.

=== Environment Variables

Environment variables can be (over)written by adding the `envOverrides` property.

For example per role group:

[source,yaml]
----
servers:
  roleGroups:
    default:
      config: {}
      envOverrides:
        MY_ENV_VAR: "MY_VALUE"
----

or per role:

[source,yaml]
----
servers:
  envOverrides:
    MY_ENV_VAR: "MY_VALUE"
  roleGroups:
    default:
      config: {}
----
