= Usage

After installation, the CRD for this operator must be created:

[source]
----
kubectl apply -f /etc/stackable/opa-operator/crd/openpolicyagent.crd.yaml
----

To create a single node OPA (v0.37.2) cluster with Prometheus metrics exposed on port 8081:

[source,yaml]
----
    apiVersion: opa.stackable.tech/v1alpha1
    kind: OpaCluster
    metadata:
      name: simple-opa
    spec:
      version: "0.37.2"
      servers:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/os: linux
----

== Bundle Sources

OPA bundles are generated from `ConfigMap` objects by a side car container running along side the OPA server.

Alternatively, the OPA servers can load bundles from a remote server when a `regoRuleReference` is configured in the role group's `config` section.

== Monitoring

The managed OPA instances are automatically configured to export Prometheus metrics. See
xref:home::monitoring.adoc[] for more details.

== Configuration & Environment Overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Do not override port numbers. This will lead to faulty installations.

=== Configuration Properties

Currently, not supported for `config.yaml`.

=== Environment Variables

Environment variables can be (over)written by adding the `envOverrides` property.

For example per role group:

[source,yaml]
----
servers:
  roleGroups:
    default:
      config: {}
      envOverrides:
        MY_ENV_VAR: "MY_VALUE"
----

or per role:

[source,yaml]
----
servers:
  envOverrides:
    MY_ENV_VAR: "MY_VALUE"
  roleGroups:
    default:
      config: {}
----
