= Implementation notes

These notes may be of use when trying to understand why things are implemented the way that they are,
but should not be required reading for regular use.

== OPA replica per node

OPA is deployed as a DaemonSet and runs on each Node. two entrypoint Services are defined.

=== Local Traffic Policy

OPA runs on each Node to avoid requiring network round trips for services making policy queries (which are often chained in serial, and block other tasks in the products).

Local access is ensured via an https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/[`InternalTrafficPolicy`].
This means that https://kubernetes.io/docs/concepts/workloads/pods/[Pods] accessing OPA via the service discovery are routed to the OPA Pod on the same https://kubernetes.io/docs/concepts/architecture/nodes/[Node] to reduce request latency and network traffic.

This should be the default entrypoint and has the same name as the defined OPA cluster.

If the `metadata.name` is `opa`, this service is called `opa-local`.

=== Cluster Traffic Policy (round-robin)

This service is called as the OPA cluster suffixed with `-cluster`. This entrypoint can be used if latency (e.g. no network requests) is less important.
Evaluating complicated rego rules may take some time depending on the provided resources, and can be the limiting factor in e.g. bulk requests.
Therefore, using this service, every Pod in the cluster is utilized to evaluate policies (via round robin). This allows better parallelism when
evaluating policies, but results in network roundtrips.

If the `metadata.name` is `opa`, this service is called `opa-cluster`.

== OPA Bundle Builder

Users can manage policy rules by creating, updating and deleting ConfigMap resources.

The responsibility of the https://github.com/stackabletech/opa-bundle-builder[OPA Bundle Builder] is to convert these resources to bundles (`tar.gz` files) and make them available via an HTTP endpoint.
The OPA Bundle Builder runs in a side container of the OPA Pod as a simple HTTP server that OPA is querying regularly
(every 20 to 30 seconds) for updates.

NOTE: Kubernetes limits the size of ConfigMaps to 1MB.
Users have to take this limit into consideration when managing policy rules.

Only ConfigMaps labeled with `opa.stackable.tech/bundle: "true"` are considered by the builder when updating bundles. The name of
the `data` entries in the `ConfigMap` are used as file names when storing the rules in the bundle.

NOTE: Currently, it is the user's responsibility to make sure these names do not collide (as they will override each other).
