= Stackable Operator for OPA (OpenPolicyAgent)
:description: The Stackable Operator for OPA is a Kubernetes operator that manages OPA instances. Learn about its features, resources, dependencies and demos, and see the list of supported OPA versions.
:keywords: Stackable Operator, OPA, OpenPolicyAgent, Rego, Kubernetes, k8s, operator, engineer, policy

The Stackable Operator for the OpenPolicyAgent (OPA) manages OPA instances. OPA is an open-source policy engine that allows you to define, manage and enforce policies across a number of software systems. OPA promotes "policy-as-code"; policies are defined in the declarative Rego language.

== Getting started

== Operator model

TODO

image::opa_overview.drawio.svg[A diagram depicting the Kubernetes resources created by the Stackable Operator for OPA]

== Dependencies and other Operators to connect to

no dependencies at all (not even secret, commons)

TODO which operator use it so far? .... Druid, Trino, Kafka

// currently no demos

== Supported Versions

The Stackable Operator for OPA currently supports the following versions of OPA:

include::partial$supported-versions.adoc[]
