apiVersion: opa.stackable.tech/v1alpha1
kind: OpenPolicyAgent
metadata:
  name: simple
spec:
  version: "0.27.1"
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        config:
          port: 8181
          repoRuleReference: "http://192.168.178.27:3030/opa/v1"
