---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-bundle-druid
  labels:
    opa.stackable.tech/bundle: "true"
data:
  trino.rego: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
    player.maximum-speed=5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-bundle-trino
  labels:
    opa.stackable.tech/bundle: "true"
data:
  trino.rego: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
