= Discovery
:description: Discover OPA cluster connection strings for internal access, including URL configuration for querying policies.
:page-aliases: discovery.adoc
:clusterName: simple-opa
:namespace: stackable
:packageName: opa-test
:policyName: allow

The Stackable operator for OpenPolicyAgent (OPA) publishes a xref:concepts:service-discovery.adoc[discovery ConfigMap], which exposes a client configuration bundle that allows access to the OPA cluster.

The bundle includes a connection string to access the OPA cluster.
This string may be used by other operators or tools to configure their products with access to OPA.
This is limited to internal cluster access.

== Example

Given the following OPA cluster:

[source,yaml,subs="normal,callouts"]
----
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: {clusterName} # <1>
  namespace: {namespace} # <2>
spec:
  [...]
----
<1> The name of the OPA cluster, which is used in the created discovery ConfigMaps.
<2> The namespace of the discovery ConfigMaps.

Currently, three discovery ConfigMaps are provided.

=== (DEPRECATED) Internal Traffic Policy `Local` 

The discovery ConfigMap `{namespace}/{clusterName}` contains the following fields where `{clusterName}` represents the name and `{namespace}` the namespace of the cluster.
This is deprecated and only kept for backwards compatibitliy. Users are adviced to switch to `{namespace}/{clusterName}-local`, which is the identical replacement.

`OPA`::
====
A connection string for cluster internal OPA requests.
Provided the cluster example above, the connection string is created as follows:

[subs="attributes"]
    http://{clusterName}.{namespace}.svc.cluster.local:8081/

This connection string points to the base URL (and web UI) of the OPA cluster.
In order to query policies you have to configure your product and its OPA URL as follows, given the bundle package name `{packageName}` and the policy name `{policyName}`:

[subs="attributes"]
    http://{clusterName}.{namespace}.svc.cluster.local:8081/v1/data/{packageName}/{policyName}
====

=== Internal Traffic Policy `Local` 

The discovery ConfigMap `{namespace}/{clusterName}-local` contains the following fields where `{clusterName}-local` represents the name and `{namespace}` the namespace of the cluster.
Using this discovery service, requests from one Node will always reach the OPA Pod on the same Node. This allows for low latency authorization queriers.

`OPA`::
====
A connection string for cluster internal OPA requests.
Provided the cluster example above, the connection string is created as follows:

[subs="attributes"]
    http://{clusterName}-local.{namespace}.svc.cluster.local:8081/

This connection string points to the base URL (and web UI) of the OPA cluster.
In order to query policies you have to configure your product and its OPA URL as follows, given the bundle package name `{packageName}` and the policy name `{policyName}`:

[subs="attributes"]
    http://{clusterName}-local.{namespace}.svc.cluster.local:8081/v1/data/{packageName}/{policyName}
====

=== Internal Traffic Policy `Cluster` 

The discovery ConfigMap `{namespace}/{clusterName}-cluster` contains the following fields where `{clusterName}-cluster` represents the name and `{namespace}` the namespace of the cluster.
Using this discovery service, requests to OPA are distributed over all available OPA Pods, improving parallelism when evaluating policies but slightly increasing the latency of each single query
to due additional network requests.

`OPA`::
====
A connection string for cluster internal OPA requests.
Provided the cluster example above, the connection string is created as follows:

[subs="attributes"]
    http://{clusterName}-cluster.{namespace}.svc.cluster.local:8081/

This connection string points to the base URL (and web UI) of the OPA cluster.
In order to query policies you have to configure your product and its OPA URL as follows, given the bundle package name `{packageName}` and the policy name `{policyName}`:

[subs="attributes"]
    http://{clusterName}-cluster.{namespace}.svc.cluster.local:8081/v1/data/{packageName}/{policyName}
====
