= Installation

On this page you will install the Stackable OPA Operator.

== Stackable Operators

There are 2 ways to run Stackable Operators

1. Using xref:stackablectl::index.adoc[] (recommended)

2. Using Helm

=== stackablectl

stackablectl is the command line tool to interact with Stackable operators and our recommended way to install Operators.
Follow the xref:stackablectl::installation.adoc[installation steps] for your platform.

After you have installed stackablectl run the following command to install the OPA Operator:

[source,bash]
----
include::example$code/getting_started.sh[tag=stackablectl-install-operators]
----

The tool will show

----
[INFO ] Installing opa operator
----

TIP: Consult the xref:stackablectl::quickstart.adoc[] to learn more about how to use stackablectl. For example, you can use the `-k` flag to create a Kubernetes cluster with link:https://kind.sigs.k8s.io/[kind].

=== Helm

You can also use Helm to install the Operator. Add the Stackable Helm repository:
[source,bash]
----
include::example$code/getting_started.sh[tag=helm-add-repo]
----

Then install the Stackable Operators:
[source,bash]
----
include::example$code/getting_started.sh[tag=helm-install-operators]
----

Helm will deploy the Operator in a Kubernetes Deployment and apply the CRDs for the OPA service. You are now ready to deploy OPA in Kubernetes.

== What's next

xref:first_steps.adoc[TODO].