apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: server.opa.stackable.tech
spec:
  group: opa.stackable.tech
  names:
    kind: OpaServer
    plural: opaservers
    shortNames:
      - os
    singular: opaserver
  scope: Namespaced
  versions:
    - additionalPrinterColumns: []
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                selectors:
                  type: array
                  items:
                    type: object
                    properties:
                      repoRuleOperatorRef:
                        type: string
                      port:
                        type: integer
              type: object
          required:
            - spec
          title: OpaServer
          type: object
      served: true
      storage: true
      subresources: {}
