apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openpolicyagents.authz.stackable.tech
spec:
  group: authz.stackable.tech
  names:
    kind: OpenPolicyAgent
    singular: openpolicyagent
    plural: openpolicyagents
    listKind: OpenPolicyAgents
    shortNames:
      - opa
  scope: Namespaced
  versions:
    - additionalPrinterColumns: []
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                port:
                  type: integer
              required:
                - port
              type: object
          required:
            - spec
          title: OpaServer
          type: object
      served: true
      storage: true
      subresources: {}
