---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  labels:
    opa.stackable.tech/bundle: "true"
data:
  test.rego: |
    package test

    hello {
      true
    }

    world {
      false
    }

    userGroups(username) := http.send({"method": "POST", "url": "http://127.0.0.1:9476/user/groups", "body": {"username": username}, "headers": {"Content-Type": "application/json"}}).body
    currentUserGroups := userGroups(input.username)
